# Generated by Django 5.2.7 on 2025-11-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacysystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='nivel_acesso',
            field=models.CharField(blank=True, choices=[('administrador', 'Administrador'), ('funcionario', 'Funcionário')], max_length=20, null=True),
        ),
    ]
